name: component_library
description: A starting point for Dart libraries or applications.
version: 1.0.0


environment:
  sdk: ^3.2.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: "iransans_en"
      fonts:
        - asset: assets/fonts/iransans_en_black.ttf
          weight: 700
        - asset: assets/fonts/iransans_en_bold.ttf
          weight: 600
        - asset: assets/fonts/iransans_en_medium.ttf
          weight: 500
        - asset: assets/fonts/iransans_en_regular.ttf
          weight: 400
        - asset: assets/fonts/iransans_en_light.ttf
          weight: 300
        - asset: assets/fonts/iransans_en_ultralight.ttf
          weight: 200
